refactors the entire project

diff --git a/defaults/bash/rc b/defaults/bash/rc
--- a/defaults/bash/rc
+++ b/defaults/bash/rc
@@ -1,4 +1,254 @@
-source ~/.local/share/quantum/defaults/bash/shell
+# shellcheck disable=SC1090
 source ~/.local/share/quantum/defaults/bash/aliases
-source ~/.local/share/quantum/defaults/bash/prompt
 source ~/.local/share/quantum/defaults/bash/init
+
+
+case $- in
+*i*) ;; # interactive
+*) return ;;
+esac
+
+# ---------------------- local utility functions ---------------------
+
+_have() { type "$1" &>/dev/null; }
+_source_if() { [[ -r "$1" ]] && source "$1"; }
+
+# ----------------------- environment variables ----------------------
+#                           (also see envx)
+
+export LANG=en_US.UTF-8 # assuming apt install language-pack-en done
+export USER="${USER:-$(whoami)}"
+export GITUSER="$USER"
+export TZ=America/New_York
+export REPOS="$HOME/repos"
+export GHREPOS="$REPOS/github.com/$GITUSER"
+export DOTFILES="$HOME/dotfiles"
+export HELP_BROWSER=lynx
+export DESKTOP="$HOME/Desktop"
+export DOCUMENTS="$HOME/Documents"
+export DOWNLOADS="$HOME/Downloads"
+export QUANTUM_PATH="/home/$USER/.local/share/quantum"
+export PUBLIC="$HOME/Public"
+export PRIVATE="$HOME/Private"
+export PICTURES="$HOME/Pictures"
+export MUSIC="$HOME/Music"
+export SCRIPTS="$HOME/bin"
+export VIDEOS="$HOME/Videos"
+export VIRTUALMACHINES="$HOME/VirtualMachines"
+export TERM=xterm-256color
+export HRULEWIDTH=73
+export EDITOR=vi
+export VISUAL=vi
+export EDITOR_PREFIX=vi
+export GOPRIVATE="github.com/$GITUSER/*,sr.ht/$GITUSER/*"
+export GOBIN="$HOME/go/bin"
+export GOPROXY=direct
+export CGO_ENABLED=0
+export LC_COLLATE=C
+export CFLAGS="-Wall -Wextra -Werror -O0 -g -fsanitize=address -fno-omit-frame-pointer -finstrument-functions"
+
+export LESS="-FXR"
+export LESS_TERMCAP_mb="␛[35m" # magenta
+export LESS_TERMCAP_md="␛[33m" # yellow
+export LESS_TERMCAP_me=""      # "␛0m"
+export LESS_TERMCAP_se=""      # "␛0m"
+export LESS_TERMCAP_so="␛[34m" # blue
+export LESS_TERMCAP_ue=""      # "␛0m"
+export LESS_TERMCAP_us="␛[4m"  # underline
+
+export DOCKER_HOST=unix:///run/user/$(id -u)/docker.sock
+
+# -------------------------------- gpg -------------------------------
+
+export GPG_TTY=$(tty)
+
+# ------------------------------- pager ------------------------------
+
+if [[ -x /usr/bin/lesspipe ]]; then
+	export LESSOPEN="| /usr/bin/lesspipe %s"
+	export LESSCLOSE="/usr/bin/lesspipe %s %s"
+fi
+
+# ------------------------------- path -------------------------------
+
+pathappend() {
+	declare arg
+	for arg in "$@"; do
+		test -d "$arg" || continue
+		PATH=${PATH//":$arg:"/:}
+		PATH=${PATH/#"$arg:"/}
+		PATH=${PATH/%":$arg"/}
+		export PATH="${PATH:+"$PATH:"}$arg"
+	done
+} && export -f pathappend
+
+pathprepend() {
+	for arg in "$@"; do
+		test -d "$arg" || continue
+		PATH=${PATH//:"$arg:"/:}
+		PATH=${PATH/#"$arg:"/}
+		PATH=${PATH/%":$arg"/}
+		export PATH="$arg${PATH:+":${PATH}"}"
+	done
+} && export -f pathprepend
+
+# remember last arg will be first in path
+pathprepend \
+	"$HOME/.local/bin" \
+	"$QUANTUM_PATH/bin" \
+	/usr/local/go/bin \
+	/usr/local/bin \
+	"$SCRIPTS"
+
+pathappend \
+	'/mnt/c/Windows' \
+	'/mnt/c/Program Files (x86)/VMware/VMware Workstation' \
+	/mingw64/bin \
+	/usr/local/bin \
+	/usr/local/sbin \
+	/usr/local/games \
+	/usr/games \
+	/usr/sbin \
+	/usr/bin \
+	/snap/bin \
+	/sbin \
+	/bin
+
+# ------------------------------ cdpath ------------------------------
+
+export CDPATH=".:$GHREPOS:$DOTFILES:$REPOS:$HOME"
+
+# ------------------------ bash shell options ------------------------
+
+# shopt is for BASHOPTS, set is for SHELLOPTS
+
+shopt -s checkwinsize # enables $COLUMNS and $ROWS
+shopt -s expand_aliases
+shopt -s globstar
+shopt -s dotglob
+shopt -s extglob
+
+#shopt -s nullglob # bug kills completion for some
+#set -o noclobber
+
+# -------------------------- stty annoyances -------------------------
+
+#stty stop undef # disable control-s accidental terminal stops
+stty -ixon # disable control-s/control-q tty flow control
+
+# ------------------------------ history -----------------------------
+
+export HISTCONTROL=ignoreboth
+export HISTSIZE=5000
+export HISTFILESIZE=10000
+
+set -o vi
+shopt -s histappend
+
+# --------------------------- smart prompt ---------------------------
+#                 (keeping in bashrc for portability)
+
+PROMPT_LONG=20
+PROMPT_MAX=95
+PROMPT_AT=@
+
+__ps1() {
+	local P='$' dir="${PWD##*/}" B countme short long double \
+		r='\[\e[31m\]' g='\[\e[30m\]' h='\[\e[34m\]' \
+		u='\[\e[33m\]' p='\[\e[34m\]' w='\[\e[35m\]' \
+		b='\[\e[36m\]' x='\[\e[0m\]'
+
+	[[ $EUID == 0 ]] && P='#' && u=$r && p=$u # root
+	[[ $PWD = / ]] && dir=/
+	[[ $PWD = "$HOME" ]] && dir='~'
+
+	B=$(git branch --show-current 2>/dev/null)
+	[[ $dir = "$B" ]] && B=.
+	countme="$USER$PROMPT_AT$(hostname):$dir($B)\$ "
+
+	[[ $B == master || $B == main ]] && b="$r"
+	[[ -n "$B" ]] && B="$g($b$B$g)"
+
+	short="$u\u$g$PROMPT_AT$h\h$g:$w$dir$B$p$P$x "
+	long="$g╔ $u\u$g$PROMPT_AT$h\h$g:$w$dir$B\n$g╚ $p$P$x "
+	double="$g╔ $u\u$g$PROMPT_AT$h\h$g:$w$dir\n$g║ $B\n$g╚ $p$P$x "
+
+	if ((${#countme} > PROMPT_MAX)); then
+		PS1="$double"
+	elif ((${#countme} > PROMPT_LONG)); then
+		PS1="$long"
+	else
+		PS1="$short"
+	fi
+}
+
+PROMPT_COMMAND="__ps1"
+
+# ----------------------------- keyboard -----------------------------
+
+# only works if you have X and are using a tiling WM. For a desktop,
+# using Gnome, the below command will get set.
+
+_have setxkbmap && test -n "$DISPLAY" &&
+	setxkbmap -option ctrl:swapcaps &>/dev/null
+
+gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:swapcaps']"
+
+# ------------------------------ aliases -----------------------------
+#      (use exec scripts instead, which work from vim and subprocs)
+
+unalias -a
+alias ip='ip -c'
+alias '?'=llm
+alias dot='cd $DOTFILES'
+alias scripts='cd $SCRIPTS'
+alias la='ls -la --color=auto'
+alias free='free -h'
+alias tree='tree -a'
+alias df='df -h'
+alias chmox='chmod +x'
+alias diff='diff --color'
+alias temp='cd $(mktemp -d)'
+alias more="less"
+
+_have nvim && alias vi=vim
+
+# ----------------------------- functions ----------------------------
+
+# lesscoloroff() {
+#   while IFS= read -r line; do
+#     unset ${line%%=*}
+#   done < <(env | grep LESS_TERM)
+# } && export -f lesscoloroff
+
+envx() {
+	local envfile="${1:-"$HOME/.env"}"
+	[[ ! -e "$envfile" ]] && echo "$envfile not found" && return 1
+	while IFS= read -r line; do
+		name=${line%%=*}
+		value=${line#*=}
+		[[ -z "${name}" || $name =~ ^# ]] && continue
+		export "$name"="$value"
+	done <"$envfile"
+} && export -f envx
+
+[[ -e "$HOME/.env" ]] && envx "$HOME/.env"
+
+# ------------- source external dependencies / completion ------------
+
+# for mac
+[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"
+
+_source_if /usr/share/bash-completion/bash_completion
+
+_have pandoc && . <(pandoc --bash-completion)
+_have podman && _source_if "$HOME/.local/share/podman/completion" # d
+_have docker && _source_if "$HOME/.local/share/docker/completion" # d
+_have docker-compose && complete -F _docker_compose dc            # dc
+
+# -------------------- personalized configuration --------------------
+
+_source_if "$HOME/.bash_personal"
+_source_if "$HOME/.bash_private"
+_source_if "$HOME/.bash_work"
+
